# baseURL = "https://reaganlandsurveying.com/"
baseURL = "https://ajs17.github.io/rls/"
languageCode = "en-us"
title = "Reagan Land Surveying"
publishDir = "docs" 
enableGitInfo = true
footnoteReturnLinkContents = "↩"
lastmod = [":fileModTime", ":default"] # auto populates lastmod date
paginate = "50"

[params]
  ImageMaxWidth = "1000"
  #analyticsid = ""
  #additionalmetatags = "<meta name=\"msvalidate.01\" content=\"\" />" 
  humanDateFormat = "Monday 02 Jan 2006"
  
# theming and reusable code
[module]
  [[module.imports]]
    path = "github.com/ajs17/hugo-min-components"
 
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2
